executor: lsf

jobs: 100
latency-wait: 5
rerun-incomplete: true
use-singularity: true
use-conda: true
retries: 3

default-resources:
  - lsf_queue=express
  - lsf_project=acc_PVI
  - mem_mb=25000
  - runtime=720
  - threads=4
  - span="span[hosts=1]"
